# Generated by Django 4.2.2 on 2023-06-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(max_length=2000)),
                ('author', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
